"""empty message

Revision ID: dcf97827795b
Revises: f69e2fcb81dc
Create Date: 2021-09-24 17:21:12.480357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf97827795b'
down_revision = 'f69e2fcb81dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drink_title_key', 'drink', type_='unique')
    op.drop_constraint('menu_name_key', 'menu', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('menu_name_key', 'menu', ['name'])
    op.create_unique_constraint('drink_title_key', 'drink', ['title'])
    # ### end Alembic commands ###
